apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: your-web-app-image
          imagePullPolicy: IfNotPresent
          # Установка ограничений и запросов ресурсов для контейнера
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          # Проверка готовности и жизнеспособности приложения
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              # Проверь порт
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              # Проверь порт
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: ENVIRONMENT
              value: production
